FROM node:16-alpine as build
WORKDIR /app/client
COPY . ./
RUN yarn 
RUN yarn build

FROM nginx:alpine
COPY --from=build /app/client/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]