openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: /api
    description: Optional server description, e.g. Main (production) server
paths:
  /translation:
    get:
      summary: Returns a list of translations
      description: Optional extended description in CommonMark or HTML.
      operationId: translations.get
      parameters:
        - in: query
          name: phrase
          required: true
          schema:
            type: string
          examples:
            onePhrase:
              summary: Example of a single phrase
              value: "How are you doing?"
        - in: query
          name: limit
          required: false
          schema:
            type: integer
            default: 100
        - in: query
          name: dictionary
          required: true
          schema:
            type: string
            enum: [GC_DICT, SL_DICT]
        - in: query
          name: src_lang
          required: true
          schema: 
            type: string
            enum: [EN, CH, HSR, SL, GC, DJ, JW, UNK]
          description: The source language of the phrase. Available options include en (English), ch (Chinese), and unk (Unknown).

      responses:
        '200':
          description: A response with metadata and a list of translations
          content:
            application/json:
              schema:
                type: object
                properties:
                  original_phrase:
                    type: string
                  detected_language:
                    type: string
                    enum: [en, ch, hsr, sl, gc, dj, jw, unk]
                  translations:
                    type: array
                    items:
                      $ref: '#/components/schemas/Translation'
                  errors:
                    type: array
                    items:
                      type: string
                  metadata:
                    type: object
                    properties:
                      dictionary_name: 
                        type: string
                      dictionary_url: 
                        type: string
                required:
                  - original_phrase
                  - detected_language
                  - translations
                  - metadata
  /romanizations:
    get:
      summary: Returns a Jyutping Object
      description: Optional extended description in CommonMark or HTML.
      operationId: romanizations.get
      parameters:
        - in: query
          name: phrase
          required: true
          schema:
            type: string
          examples:
            onePhrase:
              summary: Example of a single phrase
              value: "How are you doing?"
        - in: query
          name: src_lang
          required: false
          schema: 
            type: string
            default: UNK
            enum: [EN, CH, HSR, SL, GC, DJ, JW, UNK]
          description: The source language of the phrase. Available options include en (English), ch (Chinese), and default is unk (Unknown).
      responses:
        '200':
          description: A response with metadata and a list of translations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Jyutping'

  /hello_world:
    get:
      summary: Returns a simple greeting
      operationId: translations.hello_world
      responses:
        '200':
          description: A simple greeting
          content:
            text/plain:
              schema:
                type: string
                example: Hello, world!

components:
  schemas:
    Translation:
      type: object
      properties:
        english:
          type: string
        chinese:
          type: object
          properties:
            traditional:
              type: array
              items:
                type: string
            simplified:
              type: array
              items:
                type: string
            penyim:
              type: array
              items:
                type: string
            jyutping:
              type: array
              items:
                $ref: '#/components/schemas/Jyutping'
    Jyutping:
      type: object
      properties:
        HSR:
          type: string
        SL:
          type: string
        GC:
          type: string
        DJ:
          type: string
        JW:
          type: string
      required:
        - HSR
        - SL
        - GC
        - JW